name: pangeo
channels:
 - conda-forge
dependencies:
 - python=3.9
 - pangeo-notebook
 - dask-gateway
 - pip
 - act-atmos
 - cartopy
 - xarray
 - dask
 - distributed
 - numpy
 - scipy
# additional packages on top of pangeo notebook
 - pip:
    - kubernetes
    - graphviz
    - emc2
